registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  env_file:
    - .env
  volumes:
    - ${PATH_TO_REGISTRY_DIR}/data:/var/lib/registry
    - ${PATH_TO_CERTS}:/certs
    - ${PATH_TO_REGISTRY_DIR}/pswd:/auth