server:
	ansible-playbook -i hosts.yml server.yml -v

server-local:
	ansible-playbook -i hosts.yml local_server.yml -v

authorize:
	ansible-playbook -i hosts.yml authorize.yml -v

upgrade:
	ansible-playbook -i hosts.yml upgrade.yml -v
