server:
	ansible-playbook -i hosts.yml server.yml -vvvv

server-local:
	ansible-playbook -i hosts.yml local_server.yml -vvvv

authorize:
	ansible-playbook -i hosts.yml authorize.yml -vvvv

upgrade:
	ansible-playbook -i hosts.yml upgrade.yml -vvvv
